
GET http://localhost:3005/products/

###
POST http://localhost:3005/products
Content-Type: application/json

{
    "name":"Xyz",
    "price" :5000
}

###
DELETE http://localhost:3005/products/Xyz


### Get
GET http://localhost:3005/products/64ff2c33664dfcf39aa54f60
### Update
PATCH  http://localhost:3005/products/64ff2c33664dfcf39aa54f60
Content-Type: application/json

{
    "name":"Xyz updated 2"
}





###delete
DELETE  http://localhost:3005/products/test2

##tst

GET http://localhost:3005/test?name=test&price=10

###

POST http://localhost:3005/test
Content-Type: application/json

{
    "name":"test2",
    "id" :10
}
###
POST http://localhost:3005/test
Content-Type: application/x-www-form-urlencoded

name=test&price=50&school=xyz


###


POST http://localhost:3005/test
Content-Type: application/x-www-form-urlencoded

name=test&price=50